services:
  redis:
    image: redis:7
    container_name: aethertrade_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  trainer:
    build:
      context: ../backend
      dockerfile: trainer/Dockerfile
    container_name: aethertrade_trainer
    ports:
      - "8001:8001"
    depends_on:
      - redis
    volumes:
      - models:/app/models
      - logs:/app/logs
      - stock_data:/app/stock_data
    environment:
      - PYTHONUNBUFFERED=1

  simulator:
    build:
      context: ../backend
      dockerfile: simulator/Dockerfile
    container_name: aethertrade_simulator
    ports:
      - "8002:8002"
    depends_on:
      - redis
    volumes:
      - models:/app/models
      - stock_data:/app/stock_data
    environment:
      - PYTHONUNBUFFERED=1

  predictor:
    build:
      context: ../backend
      dockerfile: predictions/Dockerfile
    container_name: aethertrade_predictor
    ports:
      - "8003:8003"
    volumes:
      - ../backend/shared:/app/shared
      - models:/app/models
      - predictions_data:/app/predictions_data
      - stock_data:/app/stock_data
    depends_on:
      - redis
    environment:
      - PYTHONUNBUFFERED=1


  dashboard:
    build:
      context: ../frontend/dashboard
      dockerfile: Dockerfile
    container_name: aethertrade_dashboard
    ports:
      - "5173:5173"
    volumes:
      - ../frontend/dashboard:/app
      - /app/node_modules
    environment:
      - VUE_APP_TRAINER_URL=http://aethertrade_trainer:8001
      - VUE_APP_SIMULATOR_URL=http://aethertrade_simulator:8002

volumes:
  models:
  logs:
  predictions_data:
  redis_data:
  stock_data:

